version: "3.1"

services:
  influxdb:
    image: docker.io/bitnami/influxdb:1
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      INFLUXDB_ADMIN_USER_PASSWORD: bitnami123
      INFLUXDB_ADMIN_USER_TOKEN: admintoken123
      INFLUXDB_DB: wallstreetbets
    volumes:
      - influxdb_data:/bitnami/influxdb
    restart: always
  grafana:
    image: docker.io/bitnami/grafana:8
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: bitnami
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - data:/opt/bitnami/grafana/data
    depends_on:
      - influxdb
    restart: always
volumes:
  influxdb_data:
    driver: local
  data:
    driver: local
