version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    restart: always
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
    restart: always
volumes:
  mongodb_data:
    driver: local
